### ISSUE TITLE
Question regarding the clamp operation

### ISSUE THREAD

**Issue by ForeverZyh** [tianyu139/friendly-noise#1]
https://github.com/tianyu139/friendly-noise/blob/8aea311dfaae31bf122c986e9fec6f99ae95dd8f/dataset/poison.py#L92
https://github.com/tianyu139/friendly-noise/blob/8aea311dfaae31bf122c986e9fec6f99ae95dd8f/friendly_noise.py#L57
Hi, I am trying to apply friendly-noise to my setting. I saw you clamp the input to [0,1]. However, even with CIFAR10, the normalization will make each input channel to a N(0,1) distribution, which is not necessarily inside [0,1]. I wonder what's the rationale of clamping the input to [0,1] here. Or do you think it is actually not necessary here?

**Comment by tianyu139** [comment]
Hi Yuhao,

Thank you for the question. The clamp is applied to the input pre-normalization, which should be within [0,1].

Specifically, this section of the code
https://github.com/tianyu139/friendly-noise/blob/8aea311dfaae31bf122c986e9fec6f99ae95dd8f/friendly_noise.py#L31
removes the normalization transform, which is only applied to the unnormalized input + friendly noise here:
https://github.com/tianyu139/friendly-noise/blob/8aea311dfaae31bf122c986e9fec6f99ae95dd8f/friendly_noise.py#L58

Let me know if this addresses your concern!

**Comment by ForeverZyh** [comment]
I see. Thank you for the prompt reply.
